### ISSUE TITLE
Improve custom templates

### ISSUE THREAD

**Issue by YerkoPalma** [trainyard/choo-cli#16]
### Expected behavior

`choo-cli` should handle possible errors in custom templates and enforce _good_ templates
### Actual behavior

There's a lot of errors and edge cases that are unhandled yet:
- If one of the underscored files isn't present the generator will crash.
- If there's a change in a folder or file name, the rest of the generators won't work. For example: if instead of `pages` some template has `views` the page generator won't work. 
- The generator only clones a repo, without checking it's content.
### Proposed solutions
- Define as required only the `choo.yaml` and `package.json` files.
- Define some way to change the name of all generated components in the `choo.yaml` file, so the generator will pick it automatically. Something like

``` yaml
projectName: <%= projectName %>
pages:
  name: views
elements:
  present: false
```

will have this behaviour in the cli

``` bash
$ choo generate page about
# would generate an about.js in the views folder

$choo generate element something
'element' is disabled in this template
# show some message and skip generation
```
- After cloning, check that the `package.json` file has choo as a dependency.

**note:** This is a remynder of things to be fixed. I will fix this as soon as I can, but if anyone want to help is more than welcome, also if you find anything else to improve in custom templates please comment it here.

**Comment by MattMcFarland** [comment]
Awesome! I was also thinking the choo.yaml could have the template name and url, so that if you are wondering what template you are using you can easily see.

Another thing, is it would be nice to allow users to define and reshape tempate sections as projects evolve. Like plop!

**Comment by YerkoPalma** [comment]
@MattMcFarland We should define the properties that belong to the `choo.yaml` file. I propose the following:

``` yaml
projectName: <%= projectName %>
template:
  url: https://github.com/trainyard/choo-cli
  name: default
pages:
  name: page
  present: true
elements:
  name: element
  present: true
models:
  name: model
  present: true
required:
  - _choo.yaml
  - _editorconfig
  - _gitignore
  - _package.json
```

Thah would be the default config that contains all possible configuration, everything omitted would be default to some of that so developers can easy overwrite their config on their templates.
